name: InstallPack
'on':
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get latest release
        id: get_release
        run: |
          response=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          upload_url=$(echo "$response" | jq -r '.upload_url')
          echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
      - name: setup install
        run: sudo apt-get install binutils tar gzip
      - name: sed shell
        run: sed -i 's/\r$//' shells/publish-fpk.sh
      - name: chmod shell
        run: chmod +x shells/publish-fpk.sh
      - name: publish projects
        run: ./shells/publish-fpk.sh
      - name: upload-docker-fpk
        id: upload-docker-fpk
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./public/publish-fpk/docker/fnpackup-docker.fpk
          asset_name: fnpackup-docker-v1.1.4.fpk
          asset_content_type: application/fpk
